version: '3.2'
services:
   WinAuth:
      build:
        context: .
      image: winauth
      environment: 
        - "SHELL=powershell.exe"
      ports:
        - "80"
        - "55539"
      networks:
        - nat
networks:
  nat:
    external: true